import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import cv2
import numpy as np
from PIL import Image as PILImage
import io

class PDFReportGenerator:
    def __init__(self, filename, image_path, image_data):
        self.filename = filename
        self.image_path = image_path
        self.image_data = image_data
        self.styles = getSampleStyleSheet()
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            spaceAfter=30,
            alignment=TA_CENTER
        )
        self.heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=14,
            spaceAfter=20,
            alignment=TA_LEFT
        )
        self.normal_style = self.styles['Normal']

    def create_report(self, analysis_data, output_path):
        """Generate PDF report with analysis results"""
        doc = SimpleDocTemplate(output_path, pagesize=letter)
        story = []

        # Title page
        story.extend(self._create_title_page())

        # Original image
        story.extend(self._add_original_image())

        # Analysis results
        for analysis_name, data in analysis_data.items():
            story.extend(self._add_analysis_section(analysis_name, data))

        # Footer with timestamp
        story.extend(self._add_footer())

        doc.build(story)

    def _create_title_page(self):
        """Create title page with basic info"""
        elements = []
        elements.append(Paragraph("Digital Image Forensic Analysis Report", self.title_style))
        elements.append(Spacer(1, 0.5*inch))

        elements.append(Paragraph(f"Image: {os.path.basename(self.image_path)}", self.heading_style))
        elements.append(Paragraph(f"Analysis Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", self.normal_style))
        elements.append(Paragraph(f"Generated by: LOOK-DGC Forensic Toolkit", self.normal_style))
        elements.append(PageBreak())
        return elements

    def _add_original_image(self):
        """Add original image to report"""
        elements = []
        elements.append(Paragraph("Original Image", self.heading_style))

        # Convert numpy array to PIL Image for ReportLab
        if isinstance(self.image_data, np.ndarray):
            pil_img = PILImage.fromarray(cv2.cvtColor(self.image_data, cv2.COLOR_BGR2RGB))
        else:
            pil_img = PILImage.open(self.image_path)

        # Resize image to fit page
        max_width = 6*inch
        max_height = 4*inch
        pil_img.thumbnail((max_width, max_height), PILImage.LANCZOS)

        # Convert to bytes
        img_buffer = io.BytesIO()
        pil_img.save(img_buffer, format='PNG')
        img_buffer.seek(0)

        img = Image(img_buffer, width=pil_img.width, height=pil_img.height)
        elements.append(img)
        elements.append(Spacer(1, 0.25*inch))
        return elements

    def _add_analysis_section(self, analysis_name, data):
        """Add analysis section with results"""
        elements = []
        elements.append(Paragraph(analysis_name, self.heading_style))

        if 'text' in data:
            elements.append(Paragraph(data['text'], self.normal_style))

        if 'image' in data:
            # Handle image data
            img_data = data['image']
            if isinstance(img_data, np.ndarray):
                pil_img = PILImage.fromarray(cv2.cvtColor(img_data, cv2.COLOR_BGR2RGB))
            else:
                pil_img = PILImage.open(img_data)

            # Resize
            max_width = 5*inch
            max_height = 3*inch
            pil_img.thumbnail((max_width, max_height), PILImage.LANCZOS)

            img_buffer = io.BytesIO()
            pil_img.save(img_buffer, format='PNG')
            img_buffer.seek(0)

            img = Image(img_buffer, width=pil_img.width, height=pil_img.height)
            elements.append(img)

        if 'table' in data:
            # Handle table data
            table_data = data['table']
            table = Table(table_data)
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 14),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            elements.append(table)

        elements.append(Spacer(1, 0.25*inch))
        return elements

    def _add_footer(self):
        """Add footer with generation info"""
        elements = []
        elements.append(Spacer(1, 1*inch))
        elements.append(Paragraph(f"Report generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", self.normal_style))
        return elements

def generate_pdf_report(filename, image_path, image_data, analysis_data, output_path):
    """Convenience function to generate PDF report"""
    generator = PDFReportGenerator(filename, image_path, image_data)
    generator.create_report(analysis_data, output_path)


def generate_batch_pdf_report(title, images_data, batch_results, output_path):
    """Generate PDF report for batch analysis"""
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak, Table, TableStyle
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    from datetime import datetime
    import cv2
    from PIL import Image as PILImage
    import io

    doc = SimpleDocTemplate(output_path, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=30,
        alignment=TA_CENTER
    )
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=20,
        alignment=TA_LEFT
    )
    normal_style = styles['Normal']

    # Title page
    story.append(Paragraph(f"{title}", title_style))
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph(f"Analysis Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", normal_style))
    story.append(Paragraph(f"Generated by: LOOK-DGC Batch Analysis", normal_style))
    story.append(PageBreak())

    # Summary
    story.append(Paragraph("Batch Analysis Summary", heading_style))
    summary_data = [["Image", "Tools Run", "Results"]]
    for basename, image in images_data:
        tools = list(batch_results.get(basename, {}).keys())
        summary_data.append([basename, len(tools), "Available"])
    table = Table(summary_data)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 14),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(table)
    story.append(PageBreak())

    # Individual results
    for basename, image in images_data:
        story.append(Paragraph(f"Image: {basename}", heading_style))
        # Add thumbnail
        if isinstance(image, np.ndarray):
            pil_img = PILImage.fromarray(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
        else:
            pil_img = PILImage.open(basename)
        pil_img.thumbnail((200, 200), PILImage.LANCZOS)
        img_buffer = io.BytesIO()
        pil_img.save(img_buffer, format='PNG')
        img_buffer.seek(0)
        img = Image(img_buffer, width=pil_img.width, height=pil_img.height)
        story.append(img)
        story.append(Spacer(1, 0.25*inch))

        tool_results = batch_results.get(basename, {})
        for tool_name, data in tool_results.items():
            story.append(Paragraph(tool_name, styles['Heading3']))
            if 'text' in data:
                story.append(Paragraph(data['text'], normal_style))
            if 'image' in data:
                # Handle image
                img_data = data['image']
                if isinstance(img_data, np.ndarray):
                    pil_img = PILImage.fromarray(cv2.cvtColor(img_data, cv2.COLOR_BGR2RGB))
                else:
                    pil_img = PILImage.open(img_data)
                pil_img.thumbnail((300, 200), PILImage.LANCZOS)
                img_buffer = io.BytesIO()
                pil_img.save(img_buffer, format='PNG')
                img_buffer.seek(0)
                img = Image(img_buffer, width=pil_img.width, height=pil_img.height)
                story.append(img)
            story.append(Spacer(1, 0.1*inch))
        story.append(PageBreak())

    doc.build(story)
